paths:
  project_root: /mnt/data/users/zbc/AI4S/ProteinDesign/Dual-UQ
  pdb_cache: /mnt/data/users/zbc/AI4S/ProteinDesign/Dual-UQ/data/raw/pdb
  afdb_cache: /mnt/data/users/zbc/AI4S/ProteinDesign/Dual-UQ/data/raw/afdb
  mapping_cache: /mnt/data/users/zbc/AI4S/ProteinDesign/Dual-UQ/data/raw/mappings
  model_cache: /mnt/data/users/zbc/AI4S/ProteinDesign/Dual-UQ/checkpoints
